### ISSUE TITLE
install.sh fails

### ISSUE THREAD

**Issue by JojiiOfficial** [samrath2007/ChadCocNvim#1]
Running `install.sh` fails. Nvim does start with errors but not with errors which are expected:
```
Error detected while processing command line:
E492: Not an editor command: PackerInstall
```

The install.sh output:
```
installing packer
Linking config
old nvim config will be changed to nvim.bak if exists! :0
Nvim Config doesn't exist so creating one
cp: cannot stat 'init.lua': No such file or directory
neovim will open with some errors , just press enter
```
(notice the cp error) 

I'm using Arch linux (btw) with neovim v0.5.0

**Comment by samrathchadha** [comment]
I updated the installer and some configs, it should work now. Thank you for reporting the issue.

**Comment by JojiiOfficial** [comment]
Yes now it works. Thanks
