### ISSUE TITLE
g:dashboard_default_executive needs to be set before loading dashboard-nvim package

### ISSUE THREAD

**Issue by nbn22385** [samrath2007/ChadCocNvim#13]
The variable `g:dashboard_default_executive` needs to be set before loading the dashboard-nvim package or else the command `DashboardChangeColorscheme` will fail because vim-clap is not installed (the default executive).

https://github.com/samrath2007/kyoto.nvim/blob/cb08bc4855231651a83ec74a0a8c6422900a9e4c/lua/plugins/dashboard-config.lua#L4-L6

**Comment by samrathchadha** [comment]
Solved by [this commit](https://github.com/samrath2007/kyoto.nvim/commit/6b8c35732b8cc82ee255f5c69aeb61897ffbb195)
