### ISSUE TITLE
Settings in kyotorc/init.lua not taking affect

### ISSUE THREAD

**Issue by lukeberry99** [samrath2007/ChadCocNvim#18]
Hi, I've changed the colorscheme away from tokyo night to one that better suits the rest of my setup. I'm trying to remove the BG colors to have it transparent (my terminal is semi transparent).

Running the following works from inside vim

```vimscript
:hi! Normal ctermbg=NONE guibg=NONE
```
But setting this inside `kyotorc/init.lua` does not
```lua
vim.cmd("hi! Normal ctermbg=NONE guibg=NONE")
```
I appreciate this isn't an issue related to kyoto itself, but I only have experience with good old `vimrc` and the grand world of lua based vim is new to me, any help is greatly appreciated.

**Comment by samrathchadha** [comment]
So we don't source `kyoto/init.lua` we source `kyotorc/init.lua` and this will only work if its sourced in your `init.lua`, also to make your terminal transaprent alter `globals/init.lua` to have 
```
g.tokyonight_transparent = true
```

**Comment by lukeberry99** [comment]
Sorry, that was a typo on my part. I am using kyotorc not kyoto. If I don't use the tokyonight theme, will g.tokyonight_transparent = true still apply?

Cheers

**Comment by samrathchadha** [comment]
So did the kyotorc not being sourced check your init.lua file.

The tokyonight transparency variable is only for tokyonight

**Comment by lukeberry99** [comment]
It is being sourced, using `pcall(require, "kyotorc")` but the following rule does not seem to work. 
```lua
vim.cmd("hi! Normal ctermbg=NONE guibg=NONE")
```

If I run that inside vim though it works no problem. Not sure that the issue is in anyway related to kyoto though.

**Comment by samrathchadha** [comment]
Just make it a normal require statement

**Comment by samrathchadha** [comment]
@lukeberry99 if its a problem reopen

**Comment by lukeberry99** [comment]
Hi @samrath2007 the solution to my issue was 

```lua
vim.api.nvim_exec(
[[
  hi! Normal ctermbg=NONE guibg=NONE
]], false)
```

Instead of what I had above, cheers for your help.
