### ISSUE TITLE
What are the emojis appearing on the bottom left?

### ISSUE THREAD

**Issue by lukeberry99** [samrath2007/ChadCocNvim#20]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/1644147/132257559-d470dd38-8890-4d23-83d4-d021d5cca2aa.png">

These are (relatively) new, what plugin are they from and what purpose does it solve?

**Comment by samrathchadha** [comment]
Its just a hello from coq_nvim, I have disabled it so if you pull now it should be fine.
OR
just go to your `lua/globals/init.lua`
then add this to your coq_settings
```
g.coq_settings = {
  auto_start = "shut-up",
  keymap = {
    jump_to_mark = "<c-q>",
  },
}
```

**Comment by samrathchadha** [comment]
If you have any issues please feel free to reopen this issue or make a new one
