### ISSUE TITLE
Treesitter takes too long to parse document

### ISSUE THREAD

**Issue by ShandoTheKing** [samrath2007/ChadCocNvim#22]
So basically tree-sitter takes too long to parse files. 
![screenshot-TS-not-working](https://user-images.githubusercontent.com/85017622/132981872-912c0326-8463-488c-aff8-3536bc5866cf.png)

**Comment by samrathchadha** [comment]
How long is your file? And does this happen with a minimal treesitter config?

**Comment by ShandoTheKing** [comment]
> How long is your file?

113 lines

> does this happen with a minimal treesitter config?

idk about that but this didn't happen yesterday with NvChad

**Comment by samrathchadha** [comment]
hmm could you try raising an issue in the treesitter repo?

**Comment by ShandoTheKing** [comment]
I'll try that

**Comment by ShandoTheKing** [comment]
Ok after some ripgrep action I found out that the error is printed by coq not treesitter. I removed it and tried. But the syntax highlighting is still wrong.

**Comment by samrathchadha** [comment]
Ohh ok.. I still do feel like a config which uses these plugins isn't the issue... This may be redundant but have you run `:TSInstall <package>`?

**Comment by ShandoTheKing** [comment]
Yeah

**Comment by ShandoTheKing** [comment]
I finally found it

**Comment by ShandoTheKing** [comment]
There  was nothing wrong with Treesitter. I was just not used to the error my brain just went wonky and decided that highlighting was wrong

**Comment by ShandoTheKing** [comment]
I'm sooooo sorry about this

**Comment by ShandoTheKing** [comment]
I don't know what's wrong with me

**Comment by ShandoTheKing** [comment]
Closing because I'm an idiot

**Comment by ShandoTheKing** [comment]
Also the highlight module in treesitter off. You guys might want to turn that on.

**Comment by samrathchadha** [comment]
Thank you so much for that!
