### ISSUE TITLE
How to change :wq behaviour?

### ISSUE THREAD

**Issue by SmellsNice** [samrath2007/ChadCocNvim#27]
Currently if you :wq out of a document kyoto will open a empty buffer which you will then have to quit in order to close the nvim instance. I'd like to get rid of this if possible.

**Comment by FinnRG** [comment]
Delete these lines in `viml/maps.vim`: https://github.com/samrath2007/kyoto.nvim/blob/2f2f74249d69925d56341a2c1a2a708b0a2bb251/viml/maps.vim#L43-L45

**Comment by SmellsNice** [comment]
Thank you, solved.
