### ISSUE TITLE
Lsp code actions causing errors?

### ISSUE THREAD

**Issue by FeistyKit** [samrath2007/ChadCocNvim#28]
Whenever I try to use the code actions keybind on an error, it throws an exception: 

`Error executing vim.schedule lua callback: ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:112: attempt to concatenate field 'title' (a nil value)`

[Here is a screenshot](https://cdn.discordapp.com/attachments/849688419227533352/888760844836540416/lsp_error.png)

[Here is my kyotorc file](https://pastebin.com/kg5pBU8Q)

**Comment by samrathchadha** [comment]
I think this is a lspsaga problem so I'll wait for an update on [this](https://github.com/glepnir/lspsaga.nvim/issues/246) issue

**Comment by samrathchadha** [comment]
@FeistyKit If this is still a problem please feel free to re-open this issue
