### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by habsfanongit** [samrath2007/ChadCocNvim#7]
Great project, and I love the responsiveness 👍 
Do you have any plans to add debugging capabilities like in LunarVim?

Also, as easy as the installation, I think the ReadMe should outline the installation and troubleshooting steps for new nvim users.

**Comment by samrathchadha** [comment]
I do actually have plans for debugging, but only on require. Considering its quite easy to configure kyoto.nvim and add new plugins(I myself have ~130 lines of config) I'm currently contemplating something like templated configurations from my side. You can clone those configs into you kyotorc folder and get those working. Do you think that'll be enough or should it be out of the box?

**Comment by samrathchadha** [comment]
And for the installation, I'm going to write an installer script, but I'm horrible at shell scripts. So I'll most probably write a python script or find someone who can write shell scripts well.

**Comment by samrathchadha** [comment]
If you have any further questions about this feel free to reopen
